<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        <ApplicationIcon>./Assets/logo_big_no_bg.ico</ApplicationIcon>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	<NoWarn>CS8618;CS8509;CS0067;CS8613;CS8622;MVVMTK0034</NoWarn>
	<Company>Paradigm Reality Enhancement Labs</Company>
	<AssemblyVersion>1.1.1.0</AssemblyVersion>
	<FileVersion>1.1.1.0</FileVersion>
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**" />
        <None Update="Firmware\Binaries\BabbleFirmware1.0.bin">
          <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Firmware\Binaries\BabbleFirmware1.1.bin">
          <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Firmware\Binaries\BabbleFirmware1.2.bin">
          <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Firmware\Binaries\BabbleFirmware1.2_TrackingLossFix.bin">
          <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Firmware\Binaries\BabbleFirmware1.3.bin">
          <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Firmware\Windows\espflash.exe" Condition="$([MSBuild]::IsOSPlatform('Windows'))">
            <Link>%(RecursiveDir)\%(Filename)%(Extension)</Link>
            <TargetPath>%(RecursiveDir)\%(Filename)%(Extension)</TargetPath>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Firmware\Linux\espflash" Condition="$([MSBuild]::IsOSPlatform('Linux'))">
            <Link>%(RecursiveDir)\%(Filename)%(Extension)</Link>
            <TargetPath>%(RecursiveDir)\%(Filename)%(Extension)</TargetPath>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="font.ttf">
          <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="LocalSettings.json">
          <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>


    <ItemGroup>
        <PackageReference Include="Avalonia" Version="11.3.12" />
        <PackageReference Include="Avalonia.Controls.DataGrid" Version="11.3.12" />
        <PackageReference Include="Avalonia.Controls.ItemsRepeater" Version="11.1.5" />
        <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.12" />
        <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.12" />
        <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
        <PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" Version="11.3.12" />
        <PackageReference Include="AWSSDK.S3" Version="4.0.18.8" />
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.4" />
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.4" />
        <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.4" />
        <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.4" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.4" />
        <PackageReference Include="Microsoft.ML" Version="4.0.3" />
        <PackageReference Include="Microsoft.ML.OnnxTransformer" Version="4.0.3" />
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
        <PackageReference Include="OpenCvSharp4" Version="4.13.0.20260308" />
        <PackageReference Include="OscCore" Version="1.0.5" />
        <PackageReference Include="Project-Babble.Baballonia.OverlaySDK" Version="1.0.5-alpha" />
        <PackageReference Include="SkiaSharp" Version="3.119.2" />
        <PackageReference Include="System.Net.Http" Version="4.3.4" />
        <PackageReference Include="VRChat.OSCQuery" Version="0.0.7" />
        <PackageReference Include="System.IO.Ports" Version="10.0.4" />
        <PackageReference Include="System.Management" Version="10.0.4" />
        <PackageReference Include="System.Text.RegularExpressions" Version="4.3.1" />
        <PackageReference Include="Xaml.Behaviors.Interactions.Draggable" Version="11.3.9.5" />
    </ItemGroup>


    <ItemGroup>
      <None Update="Languages\en.json">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Languages\es.json">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Languages\ja.json">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Languages\pl.json">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Languages\zh.json">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
    </ItemGroup>


    <ItemGroup>
      <Compile Update="Views\FirmwareView.axaml.cs">
        <DependentUpon>FirmwareView.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Assets\Resources.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>Resources.resx</DependentUpon>
      </Compile>
    </ItemGroup>


    <ItemGroup>
      <UpToDateCheckInput Remove="Assets\Images\chocolate_sample.jpg" />
      <UpToDateCheckInput Remove="Assets\Images\logo_big.png" />
      <UpToDateCheckInput Remove="Assets\Images\snow.jpg" />
      <UpToDateCheckInput Remove="Assets\Images\tiny_house.jpg" />
    </ItemGroup>

	<ItemGroup>
		<None Remove="faceModel.onnx" />
		<EmbeddedResource Include="faceModel.onnx">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</EmbeddedResource>
        <EmbeddedResource Include="SteamVR\manifest.vrmanifest" Link="manifest.vrmanifest">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </EmbeddedResource>
        <EmbeddedResource Include="SteamVR\openvr_api.dll" Link="openvr_api.dll">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </EmbeddedResource>
        <EmbeddedResource Include="SteamVR\libopenvr_api.so" Link="libopenvr_api.so">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </EmbeddedResource>
		<EmbeddedResource Update="Assets\Resources.resx">
		    <Generator>PublicResXFileCodeGenerator</Generator>
		    <LastGenOutput>Resources.Designer.cs</LastGenOutput>
            <LogicalName>Baballonia.Assets.Resources.resources</LogicalName>
		</EmbeddedResource>
		<EmbeddedResource Update="Assets\Resources.es.resx">
		    <Generator>ResXFileCodeGenerator</Generator>
		    <LastGenOutput>Resources.es.Designer.cs</LastGenOutput>
            <LogicalName>Baballonia.Assets.Resources.es.resources</LogicalName>
		</EmbeddedResource>
		<EmbeddedResource Update="Assets\Resources.ja.resx">
		    <Generator>ResXFileCodeGenerator</Generator>
		    <LastGenOutput>Resources.ja.Designer.cs</LastGenOutput>
            <LogicalName>Baballonia.Assets.Resources.ja.resources</LogicalName>
		</EmbeddedResource>
		<EmbeddedResource Update="Assets\Resources.pl.resx">
		    <Generator>ResXFileCodeGenerator</Generator>
		    <LastGenOutput>Resources.pl.Designer.cs</LastGenOutput>
            <LogicalName>Baballonia.Assets.Resources.pl.resources</LogicalName>
		</EmbeddedResource>
		<EmbeddedResource Update="Assets\Resources.zh-CN.resx">
            <LogicalName>Baballonia.Assets.Resources.zh-CN.resources</LogicalName>
		</EmbeddedResource>
	</ItemGroup>
	<ItemGroup>
	  <ProjectReference Include="..\Baballonia.FastCorruptionDetector\Baballonia.FastCorruptionDetector.csproj" />
	  <ProjectReference Include="..\Baballonia.SDK\Baballonia.SDK.csproj" />
	  <ProjectReference Include="..\HyperText.Avalonia\HyperText.Avalonia\HyperText.Avalonia.csproj" />
	</ItemGroup>
	<ItemGroup>
	  <None Remove="eyeModel.onnx" />
	  <EmbeddedResource Include="eyeModel.onnx">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </EmbeddedResource>
	</ItemGroup>
	<ItemGroup>
	  <Folder Include="Firmware\Linux\" />
	  <Folder Include="Firmware\MacOS\" />
	  <Folder Include="Firmware\Windows\" />
	</ItemGroup>
	<ItemGroup>
	  <AvaloniaResource Update="Assets\Resources.resx">
	    <Generator>PublicResXFileCodeGenerator</Generator>
	    <LastGenOutput>Resources.Designer.cs</LastGenOutput>
	  </AvaloniaResource>
	</ItemGroup>

</Project>
